// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  // TODO (codelab user): Replace with your Firebase credentials

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFsBa25iKaEMfOQH5c84uXiVYyV4MUazQ',
    appId: '1:81210012885:web:d31adbe725a6a7e0bc9e5c',
    messagingSenderId: '81210012885',
    projectId: 'flutter-logowanie-1',
    authDomain: 'flutter-logowanie-1.firebaseapp.com',
    storageBucket: 'flutter-logowanie-1.appspot.com',
  );

  // Generate this file with credentials with the FlutterFire CLI

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqyvotiQApadmuv0yt7joYFx3LfW0Q4wg',
    appId: '1:81210012885:android:6dad949e38c4102cbc9e5c',
    messagingSenderId: '81210012885',
    projectId: 'flutter-logowanie-1',
    storageBucket: 'flutter-logowanie-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwTv9rG5Wb8TMGCzwq8PNfhHnGWlHqWCA',
    appId: '1:81210012885:ios:8fb7918ad23f62efbc9e5c',
    messagingSenderId: '81210012885',
    projectId: 'flutter-logowanie-1',
    storageBucket: 'flutter-logowanie-1.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwTv9rG5Wb8TMGCzwq8PNfhHnGWlHqWCA',
    appId: '1:81210012885:ios:8fb7918ad23f62efbc9e5c',
    messagingSenderId: '81210012885',
    projectId: 'flutter-logowanie-1',
    storageBucket: 'flutter-logowanie-1.appspot.com',
    iosBundleId: 'com.example.complete',
  );

}