// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  // TODO (codelab user): Replace with your Firebase credentials

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY08m4TOpgaVAyv6A1qmzG00mZeyTSndg',
    appId: '1:854710865082:web:171ffb776064e2b6724683',
    messagingSenderId: '854710865082',
    projectId: 'logowanie-firebase-39394',
    authDomain: 'logowanie-firebase-39394.firebaseapp.com',
    storageBucket: 'logowanie-firebase-39394.appspot.com',
  );

  // Generate this file with credentials with the FlutterFire CLI

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd8OMlp_3S5Nw2J0Nqw-6VWdKDOmYU6wo',
    appId: '1:854710865082:android:c5119bbaf3b9f350724683',
    messagingSenderId: '854710865082',
    projectId: 'logowanie-firebase-39394',
    storageBucket: 'logowanie-firebase-39394.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9dV9jUNVRMb_diZikWCoxeWYlu4qPoVY',
    appId: '1:854710865082:ios:b5b66f87310c0f63724683',
    messagingSenderId: '854710865082',
    projectId: 'logowanie-firebase-39394',
    storageBucket: 'logowanie-firebase-39394.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9dV9jUNVRMb_diZikWCoxeWYlu4qPoVY',
    appId: '1:854710865082:ios:b5b66f87310c0f63724683',
    messagingSenderId: '854710865082',
    projectId: 'logowanie-firebase-39394',
    storageBucket: 'logowanie-firebase-39394.appspot.com',
    iosBundleId: 'com.example.complete',
  );

}